# Generated by Django 2.0.7 on 2018-07-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('modifiable', models.BooleanField()),
                ('numberOfToppings', models.IntegerField(null=True)),
                ('smallPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('largePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('defaultPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=1000, null=True)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('orderedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('item_name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Toppings',
                'verbose_name_plural': 'Toppings',
            },
        ),
    ]
