# Generated by Django 2.0.7 on 2018-07-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toppings',
            options={},
        ),
    ]
