# Generated by Django 2.0.7 on 2018-07-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='large',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='menu',
            name='small',
            field=models.NullBooleanField(),
        ),
    ]
