# Generated by Django 2.0.7 on 2018-07-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180727_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='numberOfToppings',
            field=models.IntegerField(null=True),
        ),
    ]
