# Generated by Django 2.0.7 on 2018-07-31 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180731_1858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='submitedOrder',
        ),
    ]
