# Generated by Django 2.0.7 on 2018-07-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_menu_numberoftoppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='large',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='small',
        ),
        migrations.AddField(
            model_name='menu',
            name='size',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
