# Generated by Django 2.0.7 on 2018-07-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180728_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='size',
        ),
        migrations.AddField(
            model_name='menu',
            name='defaultPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='largePrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='smallPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
