# Generated by Django 2.0.7 on 2018-07-31 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180731_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='submitedOrder',
        ),
    ]
